[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:messenger-consume-async]
command=php /app/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M -vv
user=appuser
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startsecs=0
startretries=10
stopwaitsecs=60
stopsignal=SIGTERM
redirect_stderr=true
stdout_logfile=/var/log/supervisor/messenger-async.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:messenger-consume-failed]
command=php /app/bin/console messenger:consume failed --time-limit=3600 --memory-limit=128M -vv
user=appuser
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startsecs=0
startretries=10
stopwaitsecs=60
stopsignal=SIGTERM
redirect_stderr=true
stdout_logfile=/var/log/supervisor/messenger-failed.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
